### ISSUE TITLE
how to use selenium-maven-template

### ISSUE THREAD

**Issue by heatherita** [Ardesco/Selenium-Maven-Template#25]
I'd like to extend Selenium Maven Template with my own test code.

Is this permitted and if so, what is the best way to do this? 

1. create my own source control repo and check Selenium Maven Template in
2. fork your project on github
3. Is there a way to use your project as a library and just include that in my project?

I would prefer to do #1 or #3 but please advise. thanks!

**Comment by Ardesco** [comment]
The whole point of the template is for people to take it as a starting point, and then extend it so that it meets their own requirements.  Quite a lot of people fork it (I assume that is so that they can merge in updates to it), but if you want to just take it and check it in elsewhere feel free.

It's not really a library, it's a starting point so option 3 doesn't really work IMHO.
