### ISSUE TITLE
Best practise for code organising

### ISSUE THREAD

**Issue by SnpDeveloper** [Ardesco/Selenium-Maven-Template#42]
Hello Ardesco,

This is a lovely startup you have given for selenium starters. If possible can you add how to organise the test suite / cases?

I like to know what controls the order of execution when i have more than one test file?

**Comment by Ardesco** [comment]
Nothing controls the order of execution because tests depending upon tests is a massive code smell.  

- Each test should work in isolation and not require any input from another test to make it work.
- Each test should setup data it requires before it runs and clear down modifications it has made after it has run so that the system is in a clean known state ready for the next test

**Comment by Ardesco** [comment]
Closing this down since there have been no comments for over a month.
